version: "3.8"
services:
  db:
    image: postgres:12.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: random_cats
      POSTGRES_USER: the_cat
      POSTGRES_PASSWORD: secretcat123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - db:pgsql-server
  python:
    build: .
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
